### ISSUE TITLE
ValidationError: {'legalities': {'gladiator': ['Invalid key: Invalid enum value gladiator'], 'premodern': ['Invalid key: Invalid enum value premodern']}, '_schema': ["ScryCardSchema Unknown fields: ['cardmarket_id']"]}

### ISSUE THREAD

**Issue by p4r4d0xX** [gwax/mtg_ssm#7]
[err.txt](https://github.com/gwax/mtg_ssm/files/6021765/err.txt)

 Hi all,

i get following error during creating a new file:

...
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
marshmallow.exceptions.ValidationError: {'legalities': {'gladiator': ['Invalid key: Invalid enum value gladiator'], 'premodern': ['Invalid key: Invalid enum value premodern']}, '_schema': ["ScryCardSchema Unknown fields: ['cardmarket_id']"]}

Any suggestions?

br

**Comment by gwax** [comment]
I hadn't updated the application to handle new formats introduced to the Scryfall dataset. I have now updated this and a bunch of other things.

Please pull down version 2.2.1 and see if it works.

**Comment by gwax** [comment]
This is long since resolved.
